apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: sc-demo-keyvault-csi
  namespace: default
spec:
  provider: azure
  secretObjects:
    - secretName: kv-synced-secret
      type: Opaque
      data:
        - objectName: ConnectionString
          key: CONNECTION_STRING
  parameters:
    cloudName: AzurePublicCloud
    usePodIdentity: "false"
    useVMManagedIdentity: "true"                                     # Set to true for using managed identity
    userAssignedIdentityID: "118334dc-b3d4-4e37-a22b-bd3f9e474fa2"   # Set the clientID of the user-assigned managed identity to use
    keyvaultName: kv-aks-d01                                         # Set to the name of your key vault
    objects:  |
      array:
        - |
          objectName: ConnectionString
          objectType: secret                            # secret, key or cert
          objectVersion: ""
    tenantId: "b40a105f-0643-4922-8e60-10fc1abf9c4b"                # The tenant ID of the key vault
