apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Values.secretObject.name }}
      type: {{ .Values.secretObject.type }}
      data:
        - objectName: {{ .Values.secretObject.data.objectName }}
          key: {{ .Values.secretObject.data.key }}
  parameters:
    cloudName: {{ .Values.cloudName }}
    usePodIdentity: "{{ .Values.usePodIdentity }}"
    useVMManagedIdentity: "{{ .Values.useVMManagedIdentity }}"
    userAssignedIdentityID: "{{ .Values.userAssignedIdentityID }}"
    keyvaultName: {{ .Values.keyvaultName }}
    objects: |
      array:
        - |
          objectName: {{ .Values.secretObject.data.objectName }}
          objectType: {{ .Values.secretObject.data.objectType }}
          objectVersion: ""
    tenantId: {{ .Values.tenantId }}
